/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MyOrdersRouteImport } from './routes/my-orders'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantsIdRouteImport } from './routes/restaurants.$id'
import { Route as RestaurantOrdersRouteImport } from './routes/restaurant.orders'
import { Route as RestaurantMenuRouteImport } from './routes/restaurant.menu'
import { Route as RestaurantCampaignsRouteImport } from './routes/restaurant.campaigns'
import { Route as RestaurantAccountingRouteImport } from './routes/restaurant.accounting'
import { Route as ManagerTeamRouteImport } from './routes/manager.team'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'

const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrdersRoute = MyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIdRoute = RestaurantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RestaurantsRoute,
} as any)
const RestaurantOrdersRoute = RestaurantOrdersRouteImport.update({
  id: '/restaurant/orders',
  path: '/restaurant/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantMenuRoute = RestaurantMenuRouteImport.update({
  id: '/restaurant/menu',
  path: '/restaurant/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantCampaignsRoute = RestaurantCampaignsRouteImport.update({
  id: '/restaurant/campaigns',
  path: '/restaurant/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantAccountingRoute = RestaurantAccountingRouteImport.update({
  id: '/restaurant/accounting',
  path: '/restaurant/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerTeamRoute = ManagerTeamRouteImport.update({
  id: '/manager/team',
  path: '/manager/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/my-orders': typeof MyOrdersRoute
  '/onboarding': typeof OnboardingRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/manager/team': typeof ManagerTeamRoute
  '/restaurant/accounting': typeof RestaurantAccountingRoute
  '/restaurant/campaigns': typeof RestaurantCampaignsRoute
  '/restaurant/menu': typeof RestaurantMenuRoute
  '/restaurant/orders': typeof RestaurantOrdersRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/my-orders': typeof MyOrdersRoute
  '/onboarding': typeof OnboardingRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/manager/team': typeof ManagerTeamRoute
  '/restaurant/accounting': typeof RestaurantAccountingRoute
  '/restaurant/campaigns': typeof RestaurantCampaignsRoute
  '/restaurant/menu': typeof RestaurantMenuRoute
  '/restaurant/orders': typeof RestaurantOrdersRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/my-orders': typeof MyOrdersRoute
  '/onboarding': typeof OnboardingRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/manager/team': typeof ManagerTeamRoute
  '/restaurant/accounting': typeof RestaurantAccountingRoute
  '/restaurant/campaigns': typeof RestaurantCampaignsRoute
  '/restaurant/menu': typeof RestaurantMenuRoute
  '/restaurant/orders': typeof RestaurantOrdersRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/campaigns'
    | '/my-orders'
    | '/onboarding'
    | '/restaurants'
    | '/admin/approvals'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/users'
    | '/manager/team'
    | '/restaurant/accounting'
    | '/restaurant/campaigns'
    | '/restaurant/menu'
    | '/restaurant/orders'
    | '/restaurants/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/campaigns'
    | '/my-orders'
    | '/onboarding'
    | '/restaurants'
    | '/admin/approvals'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/users'
    | '/manager/team'
    | '/restaurant/accounting'
    | '/restaurant/campaigns'
    | '/restaurant/menu'
    | '/restaurant/orders'
    | '/restaurants/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/campaigns'
    | '/my-orders'
    | '/onboarding'
    | '/restaurants'
    | '/admin/approvals'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/users'
    | '/manager/team'
    | '/restaurant/accounting'
    | '/restaurant/campaigns'
    | '/restaurant/menu'
    | '/restaurant/orders'
    | '/restaurants/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  CampaignsRoute: typeof CampaignsRoute
  MyOrdersRoute: typeof MyOrdersRoute
  OnboardingRoute: typeof OnboardingRoute
  RestaurantsRoute: typeof RestaurantsRouteWithChildren
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ManagerTeamRoute: typeof ManagerTeamRoute
  RestaurantAccountingRoute: typeof RestaurantAccountingRoute
  RestaurantCampaignsRoute: typeof RestaurantCampaignsRoute
  RestaurantMenuRoute: typeof RestaurantMenuRoute
  RestaurantOrdersRoute: typeof RestaurantOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-orders': {
      id: '/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof MyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$id': {
      id: '/restaurants/$id'
      path: '/$id'
      fullPath: '/restaurants/$id'
      preLoaderRoute: typeof RestaurantsIdRouteImport
      parentRoute: typeof RestaurantsRoute
    }
    '/restaurant/orders': {
      id: '/restaurant/orders'
      path: '/restaurant/orders'
      fullPath: '/restaurant/orders'
      preLoaderRoute: typeof RestaurantOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/menu': {
      id: '/restaurant/menu'
      path: '/restaurant/menu'
      fullPath: '/restaurant/menu'
      preLoaderRoute: typeof RestaurantMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/campaigns': {
      id: '/restaurant/campaigns'
      path: '/restaurant/campaigns'
      fullPath: '/restaurant/campaigns'
      preLoaderRoute: typeof RestaurantCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/accounting': {
      id: '/restaurant/accounting'
      path: '/restaurant/accounting'
      fullPath: '/restaurant/accounting'
      preLoaderRoute: typeof RestaurantAccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/team': {
      id: '/manager/team'
      path: '/manager/team'
      fullPath: '/manager/team'
      preLoaderRoute: typeof ManagerTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RestaurantsRouteChildren {
  RestaurantsIdRoute: typeof RestaurantsIdRoute
}

const RestaurantsRouteChildren: RestaurantsRouteChildren = {
  RestaurantsIdRoute: RestaurantsIdRoute,
}

const RestaurantsRouteWithChildren = RestaurantsRoute._addFileChildren(
  RestaurantsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  CampaignsRoute: CampaignsRoute,
  MyOrdersRoute: MyOrdersRoute,
  OnboardingRoute: OnboardingRoute,
  RestaurantsRoute: RestaurantsRouteWithChildren,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ManagerTeamRoute: ManagerTeamRoute,
  RestaurantAccountingRoute: RestaurantAccountingRoute,
  RestaurantCampaignsRoute: RestaurantCampaignsRoute,
  RestaurantMenuRoute: RestaurantMenuRoute,
  RestaurantOrdersRoute: RestaurantOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
